apiVersion: v1
data:
  fluent-bit.conf: |-
      [SERVICE]
          flush           1
          log_level       info

      [INPUT]
          name            node_exporter_metrics
          tag             node_metrics
          scrape_interval 2

      [OUTPUT]
          Name                 opentelemetry
          Match  *
          Host                 collector
          Port                 3030
          metrics_uri          /v1/metrics
          logs_uri             /v1/logs
          traces_uri           /v1/traces
          Log_response_payload True
          tls                  off
          tls.verify           off
          # add user-defined labels
          add_label            app fluent-bit
          add_label            color blue

        # [INPUT]
        #     name            node_exporter_metrics
        #     tag             node_metrics
        #     scrape_interval 180

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: fluentbit
  name: fluentbit-cm1
