apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    # kompose.cmd: kompose convert -f ../otel/docker-compose.yaml --out ./configmap --volumes configMap
    kompose.cmd: kompose convert -f ../otel/docker-compose.yaml --out ./default
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentbit
  name: fluentbit
spec:
  selector:
    matchLabels:
      io.kompose.service: fluentbit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        # kompose.cmd: kompose convert -f ../otel/docker-compose.yaml --out ./configmap --volumes configMap
        kompose.cmd: kompose convert -f ../otel/docker-compose.yaml --out ./default
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: fluentbit
    spec:
      containers:
        - image: fluent/fluent-bit:latest
          name: fluentbit
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /fluent-bit/bin/docker-metadata.lua
              name: fluentbit-cm0
              subPath: docker-metadata.lua
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: fluentbit-cm1
              subPath: fluent-bit.conf
            - name: var-log
              mountPath: /var/log
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - configMap:
            items:
              - key: docker-metadata.lua
                path: docker-metadata.lua
            name: fluentbit-cm0
          name: fluentbit-cm0
        - configMap:
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
            name: fluentbit-cm1
          name: fluentbit-cm1
        - name: var-log
          emptyDir: {}
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
