apiVersion: v1
data:
  prometheus.yaml: "global:\n  scrape_interval: 15s \n  evaluation_interval: 15s\n\nscrape_configs:\n  - job_name: otel_collector\n    scrape_interval: 5s\n    static_configs:\n      - targets: ['collector:8889']\n\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: [ 'localhost:9090' ]\n\n\n  "
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
